apiVersion: v1
kind: Secret
metadata:
  name: {{ include "noema.fullname" . }}
  labels:
    {{- include "noema.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  apiKey: {{ .apiKey | default "" | quote }}
  webhookSecret: {{ .webhookSecret | default "" | quote }}
  githubToken: {{ .githubToken | default "" | quote }}
  llmOpenAIKey: {{ .llmOpenAIKey | default "" | quote }}
  llmAnthropicKey: {{ .llmAnthropicKey | default "" | quote }}
  postgresPassword: {{ .postgresPassword | default "" | quote }}
  redisPassword: {{ .redisPassword | default "" | quote }}
  {{- end }}