# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from noema.grpc import noema_engine_pb2 as noema__engine__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in noema_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NoemaEngineServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Think = channel.unary_unary(
                '/noema.grpc.NoemaEngineService/Think',
                request_serializer=noema__engine__pb2.ThinkRequest.SerializeToString,
                response_deserializer=noema__engine__pb2.ThinkResponse.FromString,
                _registered_method=True)
        self.ThinkStream = channel.unary_stream(
                '/noema.grpc.NoemaEngineService/ThinkStream',
                request_serializer=noema__engine__pb2.ThinkRequest.SerializeToString,
                response_deserializer=noema__engine__pb2.ThinkStatus.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/noema.grpc.NoemaEngineService/Health',
                request_serializer=noema__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=noema__engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/noema.grpc.NoemaEngineService/GetMetrics',
                request_serializer=noema__engine__pb2.MetricsRequest.SerializeToString,
                response_deserializer=noema__engine__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/noema.grpc.NoemaEngineService/CancelTask',
                request_serializer=noema__engine__pb2.CancelRequest.SerializeToString,
                response_deserializer=noema__engine__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Evolve = channel.unary_unary(
                '/noema.grpc.NoemaEngineService/Evolve',
                request_serializer=noema__engine__pb2.EvolveRequest.SerializeToString,
                response_deserializer=noema__engine__pb2.EvolveResponse.FromString,
                _registered_method=True)


class NoemaEngineServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Think(self, request, context):
        """Think - generate a solution for a task (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ThinkStream(self, request, context):
        """ThinkStream - generate a solution with streaming status updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health — liveness check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """GetMetrics — return engine metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """CancelTask — cancel a running task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evolve(self, request, context):
        """Evolve — trigger self-evolution cycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoemaEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Think': grpc.unary_unary_rpc_method_handler(
                    servicer.Think,
                    request_deserializer=noema__engine__pb2.ThinkRequest.FromString,
                    response_serializer=noema__engine__pb2.ThinkResponse.SerializeToString,
            ),
            'ThinkStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ThinkStream,
                    request_deserializer=noema__engine__pb2.ThinkRequest.FromString,
                    response_serializer=noema__engine__pb2.ThinkStatus.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=noema__engine__pb2.HealthRequest.FromString,
                    response_serializer=noema__engine__pb2.HealthResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=noema__engine__pb2.MetricsRequest.FromString,
                    response_serializer=noema__engine__pb2.MetricsResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=noema__engine__pb2.CancelRequest.FromString,
                    response_serializer=noema__engine__pb2.CancelResponse.SerializeToString,
            ),
            'Evolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Evolve,
                    request_deserializer=noema__engine__pb2.EvolveRequest.FromString,
                    response_serializer=noema__engine__pb2.EvolveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noema.grpc.NoemaEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noema.grpc.NoemaEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NoemaEngineService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Think(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noema.grpc.NoemaEngineService/Think',
            noema__engine__pb2.ThinkRequest.SerializeToString,
            noema__engine__pb2.ThinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ThinkStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/noema.grpc.NoemaEngineService/ThinkStream',
            noema__engine__pb2.ThinkRequest.SerializeToString,
            noema__engine__pb2.ThinkStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noema.grpc.NoemaEngineService/Health',
            noema__engine__pb2.HealthRequest.SerializeToString,
            noema__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noema.grpc.NoemaEngineService/GetMetrics',
            noema__engine__pb2.MetricsRequest.SerializeToString,
            noema__engine__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noema.grpc.NoemaEngineService/CancelTask',
            noema__engine__pb2.CancelRequest.SerializeToString,
            noema__engine__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noema.grpc.NoemaEngineService/Evolve',
            noema__engine__pb2.EvolveRequest.SerializeToString,
            noema__engine__pb2.EvolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
